### ISSUE TITLE
Where do I put the git checkout?

### ISSUE THREAD

**Issue by danielcompton** [martinklepsch/boot-checkouts-demo#1]
I couldn't see where to actually put the java-time project in relation to the `build.boot` file?

**Comment by martinklepsch** [comment]
Hi @danielcompton, it does not matter. I just added this to the README I hope that clears things up:

> The communication mechanism for updating a checkout is installing a new jar into your Maven repository. The location of your projects code or the code of your checkout dependency is therefore not important.
